apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDenyPrivilegedContainers
metadata:
  name: deny-privileged-containers
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]

