apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sallowedimages
spec:
  crd:
    spec:
      names:
        kind: K8sAllowedImages
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sallowedimages

        allowed := {"mycompany.registry.com"}

        violation[{"msg": msg}] {
          c := input.review.object.spec.containers[_]
          not startswith(c.image, allowed[_])
          msg := sprintf("Image not from approved registry: %v", [c.image])
        }

